# -*- coding: utf-8 -*-
"""code ptit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YKufqXkSMEUgeK-4x9RM0gVUG9FaAbY4
"""


a, k, n = input().split()
a, k, n = int(a), int(k), int(n)

res = []
# first b
b = k - (a % k)
while(b <= n - a):
    res.append(str(b))
    b += k
if(len(res) > 0):
  print(" ".join(res))
else:
  print(-1)